name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, self-hosted, macOS]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Lint
      run: Make lint

    - name: Test
      run: Make test
